import home from '../deliverables/02-interaction-design/wireframe/01_home_dashboard_wireframe.svg'
import notifications from '../deliverables/02-interaction-design/wireframe/02_push_notifications_hub_wireframe.svg'
import notificationSettings from '../deliverables/02-interaction-design/wireframe/03_notification_settings_wireframe.svg'
import service from '../deliverables/02-interaction-design/wireframe/04_service_selection_wireframe.svg'
import timeslot from '../deliverables/02-interaction-design/wireframe/05_interactive_timeslot_picker_wireframe.svg'
import multiPet from '../deliverables/02-interaction-design/wireframe/06_multi_pet_booking_wireframe.svg'
import confirmation from '../deliverables/02-interaction-design/wireframe/07_booking_confirmation_wireframe.svg'
import profiles from '../deliverables/02-interaction-design/wireframe/08_pet_profiles_management_wireframe.svg'
import medical from '../deliverables/02-interaction-design/wireframe/09_medical_profile_allergies_wireframe.svg'
import vaccination from '../deliverables/02-interaction-design/wireframe/10_digital_vaccination_health_book_wireframe.svg'
import checkin from '../deliverables/02-interaction-design/prototype/persona-1/goal-2/02_qr_intake_scan.svg'
import intake from '../deliverables/02-interaction-design/wireframe/12_live_intake_handoff_confirmation_wireframe.svg'
import handover from '../deliverables/02-interaction-design/prototype/persona-1/goal-2/06_confirmed_handoff_peace_of_mind.svg'
import tracking1 from '../deliverables/02-interaction-design/wireframe/14_live_tracking_step1_received_wireframe.svg'
import tracking2 from '../deliverables/02-interaction-design/wireframe/15_live_tracking_step2_in_progress_wireframe.svg'
import tracking3 from '../deliverables/02-interaction-design/wireframe/16_live_tracking_step3_care_completed_wireframe.svg'
import tracking4 from '../deliverables/02-interaction-design/wireframe/17_live_tracking_step4_ready_for_pickup_wireframe.svg'
import parallelTracking from '../deliverables/02-interaction-design/wireframe/18_parallel_multi_pet_tracking_wireframe.svg'
import camera from '../deliverables/02-interaction-design/wireframe/19_isolation_room_live_photo_viewer_wireframe.svg'
import discharge from '../deliverables/02-interaction-design/wireframe/20_discharge_qr_verification_wireframe.svg'
import inspection from '../deliverables/02-interaction-design/wireframe/21_before_after_inspection_report_wireframe.svg'
import review from '../deliverables/02-interaction-design/wireframe/22_service_review_5star_wireframe.svg'
import history from '../deliverables/02-interaction-design/wireframe/23_service_history_hub_wireframe.svg'
import session from '../deliverables/02-interaction-design/wireframe/24_service_session_details_wireframe.svg'
import rebook from '../deliverables/02-interaction-design/wireframe/25_one_click_rebook_modal_wireframe.svg'
import budget from '../deliverables/02-interaction-design/wireframe/26_monthly_expense_budget_tracker_wireframe.svg'
import invoice from '../deliverables/02-interaction-design/wireframe/27_digital_einvoice_summary_wireframe.svg'
import loading from '../deliverables/02-interaction-design/wireframe/state_loading_wireframe.svg'
import empty from '../deliverables/02-interaction-design/wireframe/state_empty_wireframe.svg'
import error from '../deliverables/02-interaction-design/wireframe/state_error_wireframe.svg'
import networkError from '../deliverables/02-interaction-design/wireframe/state_error_network_wireframe.svg'
import success from '../deliverables/02-interaction-design/wireframe/state_success_wireframe.svg'
import appointmentCheckin from '../deliverables/02-interaction-design/prototype/persona-1/goal-2/01_appointment_checkin_card.svg'
import medicalAlert from '../deliverables/02-interaction-design/prototype/persona-1/goal-2/03_medical_alert_intake_view.svg'
import careProtocol from '../deliverables/02-interaction-design/prototype/persona-1/goal-2/04_care_protocol_consultation.svg'
import safetyLocked from '../deliverables/02-interaction-design/prototype/persona-1/goal-2/05_intake_safety_commitment_locked.svg'
import pushReady from '../deliverables/02-interaction-design/prototype/persona-1/goal-3/04_push_notification_popup.svg'
import productVerified from '../deliverables/02-interaction-design/prototype/persona-1/goal-4/04_herbal_shampoo_product_verified.svg'
import technicianNotes from '../deliverables/02-interaction-design/prototype/persona-1/goal-4/05_technician_notes_skin_health.svg'
import productSaved from '../deliverables/02-interaction-design/prototype/persona-1/goal-4/06_save_product_for_next_care.svg'
import costBreakdown from '../deliverables/02-interaction-design/prototype/persona-2/goal-3/02_service_cost_breakdown.svg'
import monthlySummary from '../deliverables/02-interaction-design/prototype/persona-2/goal-3/04_monthly_expense_summary.svg'
import budgetPlan from '../deliverables/02-interaction-design/prototype/persona-2/goal-3/05_next_month_budget_plan.svg'
import miuTimeMatrix from '../deliverables/02-interaction-design/prototype/persona-2/goal-1/01_time_matrix_view.svg'
import miuSlotSelected from '../deliverables/02-interaction-design/prototype/persona-2/goal-1/02_slot_selection.svg'
import miuService from '../deliverables/02-interaction-design/prototype/persona-2/goal-1/03_service_selection.svg'
import miuReview from '../deliverables/02-interaction-design/prototype/persona-2/goal-1/04_booking_review.svg'
import miuSuccess from '../deliverables/02-interaction-design/prototype/persona-2/goal-1/05_instant_lock_success.svg'

export const screenAssets = { home, notifications, notificationSettings, service, timeslot, multiPet, confirmation, profiles, medical, vaccination, checkin, intake, handover, tracking1, tracking2, tracking3, tracking4, parallelTracking, camera, discharge, inspection, review, history, session, rebook, budget, invoice, loading, empty, error, networkError, success, appointmentCheckin, medicalAlert, careProtocol, safetyLocked, pushReady, productVerified, technicianNotes, productSaved, costBreakdown, monthlySummary, budgetPlan, miuTimeMatrix, miuSlotSelected, miuService, miuReview, miuSuccess } as const
export type ScreenId = keyof typeof screenAssets

export const screenNames: Record<ScreenId, string> = {
  home:'Trang chủ', notifications:'Trung tâm thông báo', notificationSettings:'Cài đặt thông báo', service:'Chọn gói dịch vụ', timeslot:'Chọn khung giờ', multiPet:'Đặt lịch nhiều thú cưng', confirmation:'Xác nhận lịch hẹn', profiles:'Quản lý hồ sơ thú cưng', medical:'Hồ sơ y tế và dị ứng', vaccination:'Sổ sức khỏe và tiêm chủng', checkin:'Mã QR tiếp nhận', intake:'Xác nhận tiếp nhận', handover:'Tiếp nhận hoàn tất', tracking1:'Tiến độ mốc 1', tracking2:'Tiến độ mốc 2', tracking3:'Tiến độ mốc 3', tracking4:'Tiến độ mốc 4', parallelTracking:'Theo dõi song song', camera:'Ảnh phòng cách ly', discharge:'Mã QR nhận bé', inspection:'Báo cáo trước và sau', review:'Đánh giá dịch vụ', history:'Lịch sử chăm sóc', session:'Chi tiết lượt chăm sóc', rebook:'Đặt lại một chạm', budget:'Ngân sách tháng', invoice:'Hóa đơn điện tử', loading:'Đang tải', empty:'Chưa có lịch đang chạy', error:'Xung đột dị ứng', networkError:'Mất kết nối', success:'Đặt lịch thành công',
  appointmentCheckin:'Lịch hẹn tiếp nhận', medicalAlert:'Cảnh báo y tế tiếp nhận', careProtocol:'Đối chiếu phương án chăm sóc', safetyLocked:'Cam kết an toàn đã khóa', pushReady:'Thông báo sẵn sàng đón', productVerified:'Sản phẩm đã xác minh', technicianNotes:'Ghi chú tình trạng da', productSaved:'Đã lưu sản phẩm ưu tiên', costBreakdown:'Phân tích chi phí', monthlySummary:'Tổng chi tiêu tháng', budgetPlan:'Kế hoạch tài chính tháng tới',
  miuTimeMatrix:'Ma trận thời gian thú cưng', miuSlotSelected:'Khung giờ phù hợp đã chọn', miuService:'Chọn dịch vụ cho Miu', miuReview:'Rà soát lịch hẹn của Miu', miuSuccess:'Đã khóa lịch cho Miu',
}
